config/routes.rb
Rails.application.routes.draw do
  get "pieces/index"
  get "pieces/new"
  get "pieces/edit"
  root "static_pages#home"
  match '/help', to: "static_pages#help", via: 'get'
  match '/about', to: "static_pages#about", via: 'get'

  resources :pieces
end

app/models/piece.rb
class Piece < ActiveRecord::Base
	
	validates :title, presence: true, uniqueness: { case_sensitive: false }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
	before_filter :get_piece_by_id, only: [ :show,
                                            :edit,
                                            :update,
                                            :destroy]

  def index
  	@pieces = Piece.all
  end

  def new
    @piece = Piece.new
  end

  def create
    @Piece = Piece.new(piece_params)
    
    if @Piece.save
      flash[:notice] = "Piece #{@Piece.title} has been created."
      redirect_to @Piece
    else
      flash[:alert] = "Piece has not been created."
      render "new"
    end
  end

  def edit
  end

  def update
    @piece.update(piece_params)
    flash[:notice] = "Piece #{@piece.title} has been updated."
    redirect_to @piece
  end

  def destroy
    piece_title=@piece.title
    @piece.destroy
    flash[:notice] = "Piece #{piece_title} has been deleted."
    redirect_to pieces_path
  end

  def show
  end

private
  def get_piece_by_id
  	@piece = Piece.where(:id => params[:id] ).first

    if !@piece 
      flash[:alert] = "The piece you were looking for could not be found."
      redirect_to pieces_path
  	end
  end

  def piece_params
    params.require(:piece).permit(
      :title,
      :published,
      :instrumentation,
      :duration,
      :last_performed,
      :notes)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "The Mysterium"
    if page_title.empty?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end

end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<p><small>&copy;2014 <a href="http://bluecrowconsulting.com">Blue Crow Consulting</a></small></p>
		<nav role="navigation">
			<ul>
          <%= render "layouts/main_menu" %>
      		</ul>
        </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
	<header id="main-header" class="navbar navbar-inverse navbar-fixed-top" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <a class="navbar-brand" href="/"><%= full_title(yield(:title)) %></a>
        </div> <!-- navbar header -->
        <nav class="navbar-collapse collapse" role="navigation">
          <ul class="nav navbar-nav pull-right">
            <%= render "layouts/main_menu" %>
          </ul>
        </nav><!--/.nav-collapse -->
      </div><!-- navbar container  -->
    </header>
</div>

app/views/layouts/_main_menu.html.erb
    <li><%= link_to "Home", root_path%></li>
    <li><%= link_to "Library", pieces_path%></li>
	<li><%= link_to "About", about_path%></li>
	<li><%= link_to "Help", help_path%></li>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shiv.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.google.com/svn/trunk/html5.js>"</script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mysterium Sheet Music Library Software" %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shiv" %>

</head>
<body>
<%= render "layouts/header" %>

<div id="main-content">
	<div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
		<%= render "layouts/footer" %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</div>

</body>
</html>

app/views/pieces/_pieces_form.html.erb
<%= form_for(@piece) do |f| %>
<% if @piece.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@piece.errors.count, "error") %> prevented this piece from being saved:
		</h2>

		<ul>
			<%= @piece.errors.full_messages.each do |msg| %> 
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<fieldset>
<ul>
	<li>
		<%=f.label :title%>
		<%=f.text_field :title%>
	</li>
	<li>
		<%=f.label :published%>
		<%=f.text_field :published%>
	</li>
	<li>
		<%=f.label :instrumentation%>
		<%=f.text_field :instrumentation%>
	</li>
	<li>
		<%=f.label :duration%>
		<%=f.text_field :duration%>
	</li>
	<li>
		<%=f.label :last_performed%>
		<%=f.text_field :last_performed%>
	</li>
	<li>
		<%=f.label :notes%>
		<%=f.text_area :notes%>
	</li>
<%= f.submit %>
<% end %>

app/views/pieces/edit.html.erb
<% provide(:title, "Edit #{@piece.title}") %>

<h1>Editing Piece <%= @piece.title %></h1>
<p>Starred fields are required.</p>

<%= render "pieces_form" %>

<nav class="pieces-nav">
<%= link_to "Go Back", piece_path(@piece), :class => "btn btn-default" %>
<%= link_to "Return to Library", pieces_path, :class => "btn btn-default" %>
</nav>

app/views/pieces/index.html.erb
<% provide(:title, 'Library') %>
<h1>The Library</h1>
<p class="lead">Click on a title to edit, or on the New button to add a library item</p>

<%= link_to "New Piece", new_piece_path, :class => "btn btn-default pull-right" %>

<table class="table table-hover table-condensed table-responsive">
	<caption>Library Pieces</caption>
	<tr>
		<th>Title</th>
		<th>Instrumentation</th>
		<th>Duration (min)</th>
		<th>Last Performed</th>
		<th>Yr Published</th>
	</tr>
	<% @pieces.each do |piece| %>		
		<tr>
			<td><%= link_to piece.title, piece_path(piece), :class => "piece-link" %></td>
			<td><%=piece.instrumentation%></td>
			<td><%=piece.duration%></td>
			<td><%=piece.last_performed.strftime(format='%m/%d/%Y')%></td>
			<td><%=piece.published.strftime(format='%Y')%></td>
		</tr>
	<% end %>
</table>

app/views/pieces/new.html.erb
<% provide(:title, "Add Piece") %>

<h1>Add New Piece</h1>
<p  class="lead">
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<%= render "pieces_form" %>

<nav class="pieces-nav">
<%= link_to "Return to Library", pieces_path, :class => "btn btn-default" %>
</nav>

app/views/pieces/show.html.erb
<% provide(:title, @piece.title) %>

<h1><%= @piece.title %></h1>

    <p>Date Published: <%=@piece.published%></p>
	<p>Instrumentation: <%=@piece.instrumentation%></p>
    <p>Duration: <%=@piece.duration%></p>
    <p>Date Last Performed: <%=@piece.last_performed%></p>
	<p>Piece Notes: <%=@piece.notes%></p>

<nav class="pieces-nav">	
<%= link_to "Edit Piece", edit_piece_path(@piece), :class => "btn btn-default" %>
<%= link_to "Delete Piece", 
	piece_path(@piece),
	method: :delete,
	data: { confirm: "Are you sure you want to delete this piece?"},
	:class => "btn btn-default" %>

<%= link_to "Return to Library", pieces_path, :class => "btn btn-default" %>
</nav>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About the Mysterium Project</h1>
<h2>Open-source Sheet Music Library Software</h2>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>How to Use this Software</h1>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/static_pages/home.html.erb
<h1>The Mysterium Library Software</h1>
<h2>Welcome to the AYS Music Library Project</h2>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>